# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:version: 0.2
run-as: root

phases:
  pre_build:
    commands:
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - mv composer.phar /usr/local/bin/composer
      - composer update
      - composer validate
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 263269128568.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started...
      - echo Building the Docker image...
      - docker build -t app .
      - docker build -f Dockerfile_Nginx -t laranginx .
      - docker tag app:latest 263269128568.dkr.ecr.ap-northeast-1.amazonaws.com/app:latest
      - docker tag laranginx:latest 263269128568.dkr.ecr.ap-northeast-1.amazonaws.com/laranginx:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 263269128568.dkr.ecr.ap-northeast-1.amazonaws.com/app:latest
      - docker push 263269128568.dkr.ecr.ap-northeast-1.amazonaws.com/laranginx:latest
      - echo Writing image definitions file...
      - printf '[{"name":"app","imageUri":"%s"}]' 263269128568.dkr.ecr.ap-northeast-1.amazonaws.com/app:latest > imagedefinitions.json
      ##- printf '[{"nginx_name":"nginx","nginx_imageUri":"%s"}]' 963939003362.dkr.ecr.ap-southeast-1.amazonaws.com/laravel-nginx:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
